# üßæ Exploratory Data Analysis (EDA) - Orders

This notebook performs a complete EDA on the `orders` dataset, including:

- General overview of the dataset  
- Basic data cleaning  
- Summary statistics  
- Visualization of numerical and categorical variables

Postgre sql connection set up

In [ ]:
import psycopg2
try:
    conn = psycopg2.connect(
        host="localhost",
        database="project",
        user="user",
        password="password",
        client_encoding='WIN1252')
    cur = conn.cursor()
    print("Successfully connected to PostgreSQL!")

except psycopg2.Error as e:
    print(f"Error connecting to PostgreSQL: {e}")

Successfully connected to PostgreSQL!

Using SQLAlchemy to Load Data from PostgreSQL into a Pandas DataFrame

In [2]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:vender2299@localhost:5432/project')

query = "SELECT * FROM orders_clean"
orders= pd.read_sql(query, con=engine)

print(orders.head())

                           order_id                   customer_trx_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp   order_approved_at  \
0    delivered      2023-10-02 10:56:00 2023-10-02 11:07:00
1    delivered      2024-07-24 20:41:00 2024-07-26 03:24:00
2    delivered      2024-08-08 08:38:00 2024-08-08 08:55:00
3    delivered      2023-11-18 19:28:00 2023-11-18 19:45:00
4    delivered      2024-02-13 21:18:00 2024-02-13 22:20:00

  order_delivered_carrier_date order_delivered_customer_date  \
0          2023-10-04 19:55:00           2023-10-10 21:25:00
1          2024-07-26 14:31:00           2024-08-07 15:27:00
2          2024-08-08 13:50:00           2024-08-17 18:06:00
3          2023-11-22 13:39:00           2023-12-02 00:28:00
4          2024-02-14 19:46:00           2024-02-16 18:17:00

  order_estimated_delivery_date
0                    2023-10-18
1                    2024-08-13
2                    2024-09-04
3                    2023-12-15
4                    2024-02-26

Using SQLAlchemy to Load Data from PostgreSQL into a Pandas DataFrame

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# üîç General overview
print("üîπ Dimensions:", orders.shape)
print("\nüîπ Columns:")
print(orders.columns)
print("\nüîπ Data types:")
print(orders.dtypes)
print("\nüîπ First 5 rows:")
print(orders.head())

# üîÅ Duplicates
duplicates = orders.duplicated()
print("\nüîÅ Duplicate rows:", duplicates.sum())
if duplicates.sum() > 0:
    print("\nüîç Showing duplicates:")
    display(orders[duplicates])

# üßº Missing values
print("\nüîπ Missing values per column:")
print(orders.isnull().sum())

# üìä Basic statistics
print("\nüìà Numerical statistics:")
print(orders.describe())

# üß† Separate columns by type
num_cols = orders.select_dtypes(include=np.number).columns
cat_cols = orders.select_dtypes(include='object').columns

print("\nüî∏ Numerical columns:", list(num_cols))
print("üî∏ Categorical columns:", list(cat_cols))

# üéØ Unique values in categorical columns
for col in cat_cols:
    print(f"\nüé≤ {col} - Unique values:")
    print(orders[col].value_counts())

# üìâ Histograms for numerical columns (if any)
if len(num_cols) > 0:
    orders[num_cols].hist(bins=30, figsize=(12, 10))
    plt.tight_layout()
    plt.show()
else:
    print("‚ùå No numerical columns available for histograms.")

# üì¶ Boxplots for numerical columns (if any)
for col in num_cols:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x=orders[col])
    plt.title(f'Outliers - {col}')
    plt.show()

üîπ Dimensions: (99441, 8)

üîπ Columns:
Index(['order_id', 'customer_trx_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date'],
      dtype='object')

üîπ Data types:
order_id                                 object
customer_trx_id                          object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

üîπ First 5 rows:
                           order_id                   customer_trx_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp   order_approved_at  \
0    delivered      2023-10-02 10:56:00 2023-10-02 11:07:00
1    delivered      2024-07-24 20:41:00 2024-07-26 03:24:00
2    delivered      2024-08-08 08:38:00 2024-08-08 08:55:00
3    delivered      2023-11-18 19:28:00 2023-11-18 19:45:00
4    delivered      2024-02-13 21:18:00 2024-02-13 22:20:00

  order_delivered_carrier_date order_delivered_customer_date  \
0          2023-10-04 19:55:00           2023-10-10 21:25:00
1          2024-07-26 14:31:00           2024-08-07 15:27:00
2          2024-08-08 13:50:00           2024-08-17 18:06:00
3          2023-11-22 13:39:00           2023-12-02 00:28:00
4          2024-02-14 19:46:00           2024-02-16 18:17:00

  order_estimated_delivery_date
0                    2023-10-18
1                    2024-08-13
2                    2024-09-04
3                    2023-12-15
4                    2024-02-26

üîÅ Duplicate rows: 0

üîπ Missing values per column:
order_id                            0
customer_trx_id                     0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

üìà Numerical statistics:
            order_purchase_timestamp              order_approved_at  \
count                          99441                          99281
mean   2023-12-31 18:22:09.696805120  2024-01-01 04:16:28.723925248
min              2022-09-04 21:15:00            2022-09-15 12:16:00
25%              2023-09-12 14:46:00            2023-09-12 23:24:00
50%              2024-01-18 23:04:00            2024-01-19 11:36:00
75%              2024-05-04 15:42:00            2024-05-04 20:35:00
max              2024-10-17 17:30:00            2024-09-03 17:40:00

        order_delivered_carrier_date  order_delivered_customer_date  \
count                          97658                          96476
mean   2024-01-05 07:44:54.673861632  2024-01-14 22:47:59.860690688
min              2022-10-08 10:34:00            2022-10-11 13:46:00
25%              2023-09-15 22:28:00            2023-09-25 22:06:45
50%              2024-01-24 16:10:30            2024-02-02 19:27:30
75%              2024-05-08 13:37:45            2024-05-15 22:48:00
max              2024-09-11 19:48:00            2024-10-17 13:22:00

       order_estimated_delivery_date
count                          99441
mean   2024-01-24 14:27:35.824056320
min              2022-09-30 00:00:00
25%              2023-10-03 00:00:00
50%              2024-02-15 00:00:00
75%              2024-05-25 00:00:00
max              2024-11-12 00:00:00

üî∏ Numerical columns: []
üî∏ Categorical columns: ['order_id', 'customer_trx_id', 'order_status']

üé≤ order_id - Unique values:
order_id
66dea50a8b16d9b4dee7af250b4be1a5    1
6ec4642f9993cc34f826cfb9068e5a2f    1
38e9133ce29f6bbe35aed9c3863dce01    1
dfc6eb45a2753ed9e6c6ef4987b44503    1
6f46d42016226f77893ed3978d6903d0    1
                                   ..
a4591c265e18cb1dcee52889e2d8acc3    1
ad21c59c0840e6cb83a9ceb5573f8159    1
949d5b44dbf5de918fe9c16f97b45f8a    1
47770eb9100c2d0c44946d9cf07ec65d    1
53cdb2fc8bc7dce0b6741e2150273451    1
Name: count, Length: 99441, dtype: int64

üé≤ customer_trx_id - Unique values:
customer_trx_id
edb027a75a1449115f6b43211ae02a24    1
f00bb12620b7b232233cace1b229db18    1
ad312389a098ceff46ce92c4595c06d0    1
a046c690e0564ffde0ce611b5eee2c30    1
3803547f820b1e10b7ad9c7985f06753    1
                                   ..
503740e9ca751ccdda7ba28e9ab8f608    1
8ab97904e6daea8866dbdbc4fb7aad2c    1
f88197465ea7920adcdbec7375364d82    1
41ce2a54c0b03bf3443c3d931a367089    1
b0830fb4747a6c6d20dea0b8c802d7ef    1
Name: count, Length: 99441, dtype: int64

üé≤ order_status - Unique values:
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64
‚ùå No numerical columns available for histograms.